In [1]:
import numpy as np

In [2]:
A = np.random.rand(50)

In [3]:
A

array([0.8261909 , 0.4801236 , 0.28189424, 0.35873784, 0.49501712,
       0.52499251, 0.65172755, 0.26462656, 0.2135778 , 0.699118  ,
       0.82150342, 0.85403564, 0.99601335, 0.94346346, 0.24268794,
       0.18438801, 0.75915321, 0.82601403, 0.34964743, 0.17663792,
       0.35604671, 0.29400883, 0.53395067, 0.62617141, 0.51016778,
       0.16078613, 0.82581101, 0.90963552, 0.49671053, 0.88838787,
       0.32648777, 0.3242819 , 0.41639497, 0.53058499, 0.68844916,
       0.45551507, 0.55690282, 0.5977739 , 0.86126625, 0.76204442,
       0.19127221, 0.10911428, 0.14271039, 0.05301639, 0.57007564,
       0.66201728, 0.1589838 , 0.52564755, 0.36123315, 0.0839568 ])

## 檢查陣列維度-shape

In [7]:
A.shape  #檢查 A 的 shape

(5, 10)

In [8]:
A.shape = (5, 10)  #更改 A 的 shape

In [9]:
A

array([[0.8261909 , 0.4801236 , 0.28189424, 0.35873784, 0.49501712,
        0.52499251, 0.65172755, 0.26462656, 0.2135778 , 0.699118  ],
       [0.82150342, 0.85403564, 0.99601335, 0.94346346, 0.24268794,
        0.18438801, 0.75915321, 0.82601403, 0.34964743, 0.17663792],
       [0.35604671, 0.29400883, 0.53395067, 0.62617141, 0.51016778,
        0.16078613, 0.82581101, 0.90963552, 0.49671053, 0.88838787],
       [0.32648777, 0.3242819 , 0.41639497, 0.53058499, 0.68844916,
        0.45551507, 0.55690282, 0.5977739 , 0.86126625, 0.76204442],
       [0.19127221, 0.10911428, 0.14271039, 0.05301639, 0.57007564,
        0.66201728, 0.1589838 , 0.52564755, 0.36123315, 0.0839568 ]])

## 轉置陣列-reshape

In [10]:
A.reshape(10, 5)

array([[0.8261909 , 0.4801236 , 0.28189424, 0.35873784, 0.49501712],
       [0.52499251, 0.65172755, 0.26462656, 0.2135778 , 0.699118  ],
       [0.82150342, 0.85403564, 0.99601335, 0.94346346, 0.24268794],
       [0.18438801, 0.75915321, 0.82601403, 0.34964743, 0.17663792],
       [0.35604671, 0.29400883, 0.53395067, 0.62617141, 0.51016778],
       [0.16078613, 0.82581101, 0.90963552, 0.49671053, 0.88838787],
       [0.32648777, 0.3242819 , 0.41639497, 0.53058499, 0.68844916],
       [0.45551507, 0.55690282, 0.5977739 , 0.86126625, 0.76204442],
       [0.19127221, 0.10911428, 0.14271039, 0.05301639, 0.57007564],
       [0.66201728, 0.1589838 , 0.52564755, 0.36123315, 0.0839568 ]])

## 拉平成一維陣列-ravel

In [11]:
A.ravel()

array([0.8261909 , 0.4801236 , 0.28189424, 0.35873784, 0.49501712,
       0.52499251, 0.65172755, 0.26462656, 0.2135778 , 0.699118  ,
       0.82150342, 0.85403564, 0.99601335, 0.94346346, 0.24268794,
       0.18438801, 0.75915321, 0.82601403, 0.34964743, 0.17663792,
       0.35604671, 0.29400883, 0.53395067, 0.62617141, 0.51016778,
       0.16078613, 0.82581101, 0.90963552, 0.49671053, 0.88838787,
       0.32648777, 0.3242819 , 0.41639497, 0.53058499, 0.68844916,
       0.45551507, 0.55690282, 0.5977739 , 0.86126625, 0.76204442,
       0.19127221, 0.10911428, 0.14271039, 0.05301639, 0.57007564,
       0.66201728, 0.1589838 , 0.52564755, 0.36123315, 0.0839568 ])

## 練習題-shape

In [13]:
B = np.arange(10)

In [14]:
B.shape

(10,)

In [15]:
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
B.shape=(2, 5)

In [17]:
B

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
B.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])