## 建立陣列、相加

In [1]:
import numpy as np

In [2]:
np1 = np.array([1, 2, 3])

In [3]:
np2 = np.array([3, 4, 5])

In [4]:
print(np1 + np2)

[4 6 8]


In [5]:
print(np1.ndim, np1.shape, np1.dtype)

1 (3,) int64


## 基礎陣列資料型態

In [9]:
a = np.array([1, 2, 3, 4, 5])

In [10]:
print("a=>{0}", format(a))

a=>{0} [1 2 3 4 5]


In [14]:
b = np.array([1.25, 2.25, 3.25, 4.25, 5.25])

In [16]:
print("b.dtype=>{0}", format(b.dtype))

b.dtype=>{0} float64


## 陣列簡單解決相乘或除的問題

In [18]:
import numpy as np

In [19]:
height=[1.73, 1.68, 1.71, 1.89, 1.79]

In [20]:
weight=[65.4, 59.2, 63.6, 88.4, 68.7]

In [21]:
np_height=np.array(height)

In [22]:
np_weight=np.array(weight)

In [25]:
bmi = np_weight / np_height ** 2

In [26]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

## 平均數、最大值及標準差 練習題

In [27]:
import numpy as np

In [28]:
grades = [77, 85, 60, 90, 66, 0, 88]

In [29]:
arr = np.array(grades)

In [30]:
arr.mean()

66.57142857142857

In [31]:
arr.max()

90

In [32]:
arr.std()

29.109925370945916

## 換算匯率 練習題

In [33]:
import numpy as np

In [34]:
prices=[1096.95, 596.95, 896.95]

In [35]:
usd2twd=31.71

In [36]:
prices = np.array(prices)

In [37]:
prices * usd2twd

array([34784.2845, 18929.2845, 28442.2845])