## axis 概念

In [1]:
import numpy as np

In [2]:
A = np.arange(10).reshape(2, 5)

In [3]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
A.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [5]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
A.sum(axis=1)

array([10, 35])

In [7]:
A.sum()

45

## array 過濾器

In [8]:
L = np.array([3, -2, -1, 5, 7, -3])

In [9]:
L[L>0]

array([3, 5, 7])

## array slicing 切割(片)

In [10]:
x = np.arange(10)

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[2:5]

array([2, 3, 4])

In [14]:
x.shape = (2, 5)

In [15]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
x[:, 1:3]

array([[1, 2],
       [6, 7]])

In [17]:
x[1, :]

array([5, 6, 7, 8, 9])

## numpy 的 zip、unzip

In [18]:
# array 的 zip
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [19]:
Z = np.c_[x, y]

In [20]:
x

array([1, 2, 3, 4])

In [21]:
y

array([5, 6, 7, 8])

In [23]:
# array 的 unzip
Z[:, 0]

array([1, 2, 3, 4])

In [25]:
Z[:, 1]

array([5, 6, 7, 8])